### ISSUE TITLE
Possibility to pass label value as a prop

### ISSUE THREAD

**Issue by andreasvirkus** [vinayakkulkarni/v-image#1]
Hi, great component! I'd love to pass the label value as a prop, something like:

`<v-image alt="alt" :name="name" :img-style="myStyle" :label="'Choose'"></v-image>`

**Comment by vinayakkulkarni** [comment]
That sounds really dope. I'll add it as a feature in next minor release.

Cheers!

**Comment by andreasvirkus** [comment]
Would the same thing be possible for the `Remove image` button element?

**Comment by vinayakkulkarni** [comment]
Fixed in [version 1.0.9](https://github.com/vinayakkulkarni/v-image/releases/tag/1.0.9)
