### ISSUE TITLE
Update Readme to show Nuxt implementation

### ISSUE THREAD

**Issue by palashmon** [vinayakkulkarni/v-image#155]
Hi, thanks for this beautiful component. 

Just wanted to say, if you could you please update the readme file to show how we can implement this component using Nuxt.js. It would really help the beginners who want to learn or try out this component in their Nuxt applications without any hassle.

Thanks!

**Comment by vinayakkulkarni** [comment]
Yea, actually I was thinking of adding a docs site like I've done in [`v-intl`](https://github.com/vinayakkulkarni/v-intl) [here](https://v-intl.netlify.app/) or in [`v-mapbox`](https://github.com/vinayakkulkarni/v-mapbox) [here](https://v-mapbox.netlify.app/)

**Comment by vinayakkulkarni** [comment]
Added it in the readme.md — https://github.com/vinayakkulkarni/v-image#usage

**Comment by palashmon** [comment]
Awesome! 🙂
